name: Docker user Image CI
on:
    push:
        branches: [ "main" ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./udagram-api-user
            file: ./udagram-api-user/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/udagram-api-user:v1
            cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/udagram-api-user:buildcache
            cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/udagram-api-user:buildcache,mode=max
